### ISSUE TITLE
Incorrect Code Generation for anonymous functions

### ISSUE THREAD

**Issue by avik-pal** [cjdoris/PackageExtensionCompat.jl#9]
`(args...) -> copy(l.weight)` gets rewritten as
```julia
args...->begin
    #= none:59 =#
    copy(l.weight)
end
```
which causes a syntax error.

Example File where this occurs: https://github.com/LuxDL/Lux.jl/blob/f34e95d17608fd1d8610792b500db091d615361c/ext/LuxFluxTransformExt.jl

**Comment by cjdoris** [comment]
Thanks - essentially a dup of #8 but I'll ensure both issues are covered by tests.
